### PR TITLE
Added onInjectedCallback

### PR DESCRIPTION
**Pull request by andiamantoukos-fadv**
The primary new feature is adding a onInjectedCallback prop. The API matches the [latest ReactSVG API for the onInjected prop](https://github.com/tanem/react-svg#api) : 

> Optional Function to call after the SVG is injected. If an injection error occurs, this function receives an Error object as the first parameter. Otherwise, the first parameter is null and the second parameter is the injected SVG DOM element. Defaults to () => {}.

- Bumped version to `2.1.0` since only a new prop was added.
- Updated ReactSVG library to major version 7 to leverage their async callback capabilities which have been added since version 4.
- Updated testing libraries (enzyme, jest, et al) in order for AnataomogramSvg component to be snapshotted as HTML instead of an Enzyme object - also reduced test boilerplate by adding [jest-enzyme](https://www.npmjs.com/package/jest-enzyme) and the corresponding testEnvironment.
- Touched up Markdown to annotate language for code snippets / added to spacing for consistency.
- Added my name to the contributors' list 😂

### CODE REVIEW

**Comment by alfonsomunozpomer** [comment]
Many thanks for the PR!

Just a couple of observations:
• In `AnatomogramSvg.test.js`, the test *should call onInjectedCallback when the svg is injected* isn’t actually verifying that the callback function has been called.
• In terms of consistency, we only use `test` instead of `it` and we don’t use semicolons in tests. Also, if you name the prop `onInjected`, I think it’ll be also consistent with other props and it’ll read more natural when you use it with e.g. Eznyme’s `simulate`.

Could you please fix the above? Other than that it looks good. Thank you for adding `jest-environment-enzyme` to clear boilerplate stuff.

**Comment by andiamantoukos-fadv** [comment]
Ah, thanks for the feedback! I definitely approve of consistency, apologies for missing some of them -the latest should reflect all the suggestions.

As for the onInjected test, that is actually testing to ensure it is being called. Based on the [jest docs for async callbacks](https://jestjs.io/docs/en/asynchronous#callbacks), the test will pass if done (and thus, onInjected) is called and fail otherwise.

**Comment by andiamantoukos-fadv** [comment]
Hey @alfonsomunozpomer, just sending a quick ping in case you missed the pushed changes to the PR!

**Review by alfonsomunozpomer — APPROVED** [review]
All good, sorry it took a while to get this merged.

**Pull request merged**
